### ISSUE TITLE
get Error: SSBL Run

### ISSUE THREAD

**Issue by windskyl** [apl-ocean-engineering/liboculus#16]
hello,
I used liboculus to save sonar pictures.
previously l used Oculus M750d, and changed to MD750d

but l got this.

- ![微信图片_20220321163551](https://user-images.githubusercontent.com/24429862/159228736-24077393-ce38-4243-b2e7-77a1d273b96b.jpg)

- ![SSBL Run error](https://user-images.githubusercontent.com/24429862/159229583-2a73ff81-ead8-41bb-be2a-fde9a9276933.jpg)

as you can see, left one is the log file when l get the SSBL error and right is when sonar is connected.
my code wasnt change,
and l used the old version which still has SSBL error reporting.

- do l need to switch to this new version of liboculus to connect MD750d?
- why l get this error from sonar while l can ping it?

Any help is useful!
sofia

**Comment by windskyl** [comment]
hello amarburg,

thank you very much for answering!!!
We look forward to hearing from you.
sofia

**Comment by windskyl** [comment]
hello amarburg, 
l came up with another question.

my controlling code will turn off the power and turn it on after 5s when sonar cant be connected.
then try to connect it after 20s, waiting for its starting process.
but l still get the SSBL Run error.
the error is still there when the above process repeats.
l can connect to it only after l use the official cable for connection the other day.

- Does it have anything to do with whether I use official cables ？

Any help is useful!
sofia

**Comment by amarburg** [comment]
Hi Sofia,

Here's the response from Blueprint:

> The "oculusMasterStatusSsblRun" flag indicates that the Oculus is presently in its bootloader mode and not running the main program. This can happen for a number of reasons - identified by observing the "OculusPauseReasonType" bits in the "status" field of the OculusStatusMsg.
> 
> Usually, if the Oculus is in the bootloader then a power dip may have occurred. The pause reason would inform you of the actual reason though.

If you are having problem with the sensor on your cables, maybe you aren't providing enough power to the sonar?

I have added an issue #17 to add additional values for OculusPauseReasonType provided by Blueprint. Once we've integrated that, you might get additional information on why the sonar has paused.

**Comment by amarburg** [comment]
Hi Sofia,

In the latest commit 438f34  I've added debug output to match the new PauseReason values from Blueprint.  Can you try this new version of the code and see what the sonar returns?

**Comment by windskyl** [comment]
hello amarburg,
thanks for your replying!

actually, l was surprising to find this:
<img width="303" alt="22-3-23-imager-but-ssblrun" src="https://user-images.githubusercontent.com/24429862/159692580-20bad2ba-31a8-46e9-97b9-54e322bf92e9.PNG">

in case you cant see it clearly,
<img width="541" alt="0" src="https://user-images.githubusercontent.com/24429862/159692904-ea8b5e90-227c-4a79-a48b-34d728612923.PNG">

and its happened more than once.

- Do you know why l got this?

Any help is useful!
sofia

**Comment by windskyl** [comment]
hello amarburg,
l found that sonar will output the header:
OCULUS_SSBL
if l received SSBL Run error.
and it will output
OCULUS_IMAGER
if it works.

but as above pics,
l received SSBL Run error when sonar give me
OCULUS_IMAGER
header.

- is this a bug?

Any help is useful!
sofia.

**Comment by amarburg** [comment]
Hm.  The big block of text (starting from the long line of **** down to "Network link speed" is a log message that is sent from the sonar and printed verbatim by the software; so if there's a difference, it's due to the sonar sending different messages.   Are the two log messages in your first post -- one showing SONAR_IMAGER and one showing SONAR_SSBL from the same sonar?   

If not, it may be a difference in firmware?

**Comment by windskyl** [comment]
hello amarburg,

l forgot about whether they are from the same sonar.
l found there is a Serial Number in field "Fixed Config". ls this the unique ID number to identify the sonar?
lf it is, then the two log messages are from different sonar.

Any help is useful!
sofia.

**Comment by amarburg** [comment]
Yes, I would expect the different serial numbers indicate different sonar units.   I think the one reporting the SSBL error has a hardware problem.  I you run it with the latest version of the code, the error code may help debug the issue.

**Comment by windskyl** [comment]
hello amarburg,

thanks for your information.
l would debug with the latest version.
> Yes, I would expect the different serial numbers indicate different sonar units. I think the one reporting the SSBL error has a hardware problem. I you run it with the latest version of the code, the error code may help debug the issue.
> […](#)
> On Mar 24, 2022, at 8:06 PM, windskyl ***@***.***> wrote: ﻿ hello amarburg, l forgot about whether they are from the same sonar. l found there is a Serial Number in field "Fixed Config". ls this the unique ID number to identify the sonar? lf it is, then the two log messages are from different sonar. Any help is useful! sofia. — Reply to this email directly, view it on GitHub, or

**Comment by windskyl** [comment]
hello amarburg,

l build liboculus.so by cmake, and use it according to the oculus_client.cpp.
but l got these:
![调用liboculus函数报错_20220329220436](https://user-images.githubusercontent.com/24429862/160629775-f9253a5a-5412-4d36-b91f-023b30a27034.jpg)

l state the io_thread_ here:
![调用liboculus函数报错_CMyServer h_20220329220436](https://user-images.githubusercontent.com/24429862/160629903-72d19930-cbee-4090-8052-b0d9984b32fc.jpg)

and my func is this:
![调用liboculus函数报错_CMyServer cpp_20220329220436](https://user-images.githubusercontent.com/24429862/160629990-f3c76fdf-92ff-4117-afe7-f2f428384f97.jpg)

l run open_sonar_independently() after power it on and wait 20s.

- how do l fix it out?

Any help is useful!
sofia.

**Comment by amarburg** [comment]
Do you still get the error if you comment out the two `setCallback()` calls?   Passing in the nullptr shouldn't be necessary,

**Comment by windskyl** [comment]
yes, that is what l mean.
l forgot to delete these two lines

**Comment by amarburg** [comment]
Sorry, do you still get the segfault after you delete those two lines?

**Comment by windskyl** [comment]
yes

**Comment by lauralindzey** [comment]
Closing issue. The original discussion about SSBL RUN has been resolved; rest of discussion was requesting help debugging a segfault in @windskyl's code.
