### ISSUE TITLE
Update OculusPauseReasonType

### ISSUE THREAD

**Issue by amarburg** [apl-ocean-engineering/liboculus#17]
> The "oculusMasterStatusSsblRun" flag indicates that the Oculus is presently in its bootloader mode and not running the main program. This can happen for a number of reasons - identified by observing the "OculusPauseReasonType" bits in the "status" field of the OculusStatusMsg.
> 
> Usually, if the Oculus is in the bootloader then a power dip may have occurred. The pause reason would inform you of the actual reason though.
> 
> For reference, here is the update enumeration for the OculusPauseReasonType:

![noname](https://user-images.githubusercontent.com/122743/159532305-cbbac69d-d3c6-4a5e-b528-1e05586d5a76.png)

**Comment by lauralindzey** [comment]
@amarburg -- was there more outstanding work to be done here, or should this have been closed by #18?

**Comment by amarburg** [comment]
Should have been closed by #18
