### ISSUE TITLE
Gain Percent Not Adjusting Oculus Gain

### ISSUE THREAD

**Issue by silent-code** [apl-ocean-engineering/liboculus#21]
I'm attempting to modify the gain percent value using the  config.setGainPercent method in the configuration section of oculus_client.cpp. However, setting the percentage value does not appear to have any effect on the oculus image data. 

I have made sure the logs show that send gain and gain assistance are both 1.

Any advice on this matter would greatly appreciated.

v/r
Tim

**Comment by silent-code** [comment]
8 bit

**Comment by amarburg** [comment]
Hm.   We'll have our Oculus back in the water later this week and can try to replicate.   Just to clarify, you've hacked on `oculus_client.cpp` so [line 123](https://github.com/apl-ocean-engineering/liboculus/blob/c074481a3c22ddd706a618b7bb98b4b4c99c59ae/tools/oculus_client.cpp#L123) is something like:

```
if (bitDepth == 8) {
    config.sendGain().setGainPercent(80).setDataSize(dataSize8Bit);
  } else ...
```

and finding that changing 80 has no effect?

**Comment by silent-code** [comment]
@amarburg That is correct. I have tested changing the gain with the Oculus ViewPoint software and it does change, however.

Thanks for the help!

**Comment by amarburg** [comment]
Hm, I know it works in general since we use it in our ROS wrapper.   Let me have a look when I can actually run the sonar.

FWIW, "sendGain()" controls whether the sonar sends gain values back (one per range) with the image data.   This provides some metadata on what their time (range)-varying gain is doing.  So I don't think it's part of this issue (unless there's a bug somewhere).

"gainAssistance" isn't documented by Oculus, don't know what it does.

**Comment by amarburg** [comment]
Sorry it took so long to get back to this.  FWIW these results are with out M3000d which I received in ~June.   I don't have a non-ROS toolchain for visualizing the images themselves, so my data is all circumstantial.  And these results are all with 58e3c7e53 which I just pushed.  It modifies `oc_client` to (a) accept a gain on the command line,  (b) compute the average pixel intensity over each sonar image as it's received, and (c) reports the `gainPercent` field from the SimpleFireMessage received from the sonar.   `gainPercent` does not seem to track the requested gain.  Instead it seems to move proportionally between 40 and 100 so maybe ... it's a dB gain?   Dunno.

`oc_client -vvv --bits 8 --gain 1 -n 1` produces a `gainPercent` of 40.6 and an average intensity (for a randomly selected frame) of 0.422

`oc_client -vvv --bits 8 --gain 50 -n 1` produces a `gainPercent` of 70 and an average intensity (for a randomly selected frame) of 0.682

`oc_client -vvv --bits 8 --gain 75 -n 1` produces a `gainPercent` of 85 and an average intensity (for a randomly selected frame) of 0.73

`oc_client -vvv --bits 8 --gain 100 -n 1` produces a `gainPercent` of 100 and an average intensity (for a randomly selected frame) of 1.144


Obviously the average intensities are point samples of a time varying value, but I see a general trend that the image intensity is increasing.  And as I said above, I **can** validate that  gain is effective when I use my full set of ROS tools (which build on liboculus).

**Comment by silent-code** [comment]
Thanks for the details!
