### ISSUE TITLE
question about Beamwidth info in Constants.h

### ISSUE THREAD

**Issue by linzha0** [apl-ocean-engineering/liboculus#27]
Hi, thanks for sharing this awesome driver for Oculus sonar. We are trying to use this for our M750d sonar. However, our sonar is an old version, which means the 1.2MHz elevation beamwidth is 12 degrees (the new one is 20 degrees). 

I checked the code seems like the liboculus::Oculus_1200MHz is not actually used for driver purposes. Just double check if it's correct. 
Thanks for your time.

**Comment by amarburg** [comment]
Thanks!   You are correct, the constants are available as metadata for use by other programs that might consume the sonar data, but are not essential for actually talking to or processing the data.

We don't have a M750d to test against, so we didn't add constants for it.   Please feel free to submit a pull request which adds the beamwidth for the 750d in 1.2MHz mode.

**Comment by amarburg** [comment]
Hi @linzha0  I've just merged the ["alt_constants" API](https://github.com/apl-ocean-engineering/liboculus/pull/29) into the main branch, so you should be able to switch back to main at your convenience.

**Comment by linzha0** [comment]
thank you so much for your help. 👍🏼
