### ISSUE TITLE
using problem

### ISSUE THREAD

**Issue by WaHa-World** [apl-ocean-engineering/liboculus#31]
I would like to ask, does the sonar need a wired connection to use this project? Can I control remote sonar locally over the network? Thank you very much!

**Comment by amarburg** [comment]
All Oculus sonars are ethernet based, so you can control the sonar from any other host on the ethernet network.

**Comment by WaHa-World** [comment]
Thank you!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apl-ocean-engineering/liboculus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月20日(星期五) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apl-ocean-engineering/liboculus] using problem (Issue #31)





 
All Oculus sonars are ethernet based, so you can control the sonar from any other host on the ethernet network.
