### ISSUE TITLE
.oculus format

### ISSUE THREAD

**Issue by WaHa-World** [apl-ocean-engineering/liboculus#32]
Hi, thank you for sharing your project. Is this project still unable to read or save data in .oculus format?

**Comment by amarburg** [comment]
Hi, thanks for the issue.   Unfortunately, the `.oculus` format recorded by the Blueprint viewer is proprietary; we don't have the format information from them.  So right now we have no plans to read or write the format.

If someone were to negotiate with Blueprint to release details of the file format, I'd be happy to add support.
