### ISSUE TITLE
Does not build on a 32 bit computer.

### ISSUE THREAD

**Issue by loguna123** [apl-ocean-engineering/liboculus#4]
It seems like I having trouble building it on a 32 bit system (./fips build).
I tried to build it on a raspberry pi, doesn't work. 
No issues on building on a normal x64 linux system tho.

**Comment by amarburg** [comment]
What errors are you getting when you try to build it on the Pi?

**Comment by amarburg** [comment]
I've just confirmed that I can build it on the Raspi4 I have here with a reasonably recent version of Rasperry Pi OS Lite.   I don't have a sonar with me so I can't verify functionality.   Maybe a dependency issue?

**Comment by loguna123** [comment]
Hi,
I manage to solve the problem by changing the dependency to depend on python3 instead of 2. 
Now after i plug into the real sonar and run, it give me a raw data file. 
Any suggestion to open the file and display the sonar if possible?

**Comment by amarburg** [comment]
We have not been using the fips-based libraries for a while so they have suffered a bit of rot.    If you want a minimal solution, [libdraw_sonar](https://github.com/apl-ocean-engineering/libdraw_sonar) contains functions to draw Oculus sonar data.  There really should be a minimal example for libdraw_sonar which consumes Oculus and just draws it to an OpenCV window, but I'm afraid we don't have that right now.

Recently, most of our effort has been focused on ROS, so the ecosystem there is more mature.    If you are willing/able to run ROS, then [oculus_sonar_ros](https://gitlab.com/apl-ocean-engineering/oculus_sonar_ros) is a ROS node built around this repo.   And libdraw_sonar contains a node that takes in the SonarImage message and produces an Image topic you can view in rqt, etc.

**Comment by amarburg** [comment]
I've written a very trivial Oculus GUI which strings together liboculus and libdraw_sonar -> [trivial_oculus_gui](https://github.com/amarburg/trivial_oculus_gui).   I can confirm that it builds with fips, I am not able to test it with a sonar.  Let me know if it's helpful.
