### ISSUE TITLE
Wrong Pingrate

### ISSUE THREAD

**Issue by HikariS97** [apl-ocean-engineering/liboculus#5]
Have set ping rate to pingRateHighest, but got only around 30Hz. My sonar is M750d.

**Comment by HikariS97** [comment]
OK, range depends...

**Comment by amarburg** [comment]
That was my first thought.  The achievable ping rate will depend on the physics of the sound and the total travel time.

That said, for some versions of the Oculus firmware, we've had inconsistent results at some ping rates ... particularly odd phantom issues where switching from ping rate A to B causes the sonar to ping at B.   But then switching back to A causes the sonar to ping at some third rate C.
