### ISSUE TITLE
Question on StatusRx

### ISSUE THREAD

**Issue by HikariS97** [apl-ocean-engineering/liboculus#7]
Hi, I'm recently working on Oculus Sonar (again....)

I'm now coding on WSL2, and the sonar client is working on a, relatively,  subnet of Sonar.
So, I can't use "auto" to detect oculus automatically, because the udp package can't be transferred through router ( I'm not familiar with the mechanism of how router is working.) So I have to use a determined ip addr to trigger DataRx connection.

My question is, at this time, I can't receive status msg from sonar, right? Status msg transferred by UDP protocol, if I'm in a subnet, then I can't get status msg anymore by default router settings.

**Comment by amarburg** [comment]
I can't speak to your network configuration specifically, but yes, if the router doesn't pass the UDP broadcast "Status" messages from the sonar, then you can't use that functionality to automatically detect the sonar.

However, you can provide the sonar's IP address (as a string) to the constructor to SonarClient, in which case  you don't need status messages at all.

The only minor downside to not getting the status messages is that they do contain valuable information about the sonar's error state (for example over temperature).
