### ISSUE TITLE
Unpacking .oculus files

### ISSUE THREAD

**Issue by Firzen9** [apl-ocean-engineering/liboculus#9]
Hi,

I am working on a thesis project and would like to unpack data from the oculus m750d ping logs (which are saved in .oculus format). Is it possible to unpack the bytestreams from this or do I need access to raw ethernet data? If so, how do I access it? (would it be via a ROStopic?)

Any help would be appreciated.

Best,
Shaurya

**Comment by Firzen9** [comment]
Hi Aaron,

Sorry for any trouble again. I am running into an error with fips build. I have tried with different python environments on conda as well. 
I also tried using catkin but I get 'Command 'vcs' not found, but there are 17 similar ones'.

`=== building: linux-make-debug
=== generating: linux-make-debug
config file: /home/shaurya/fips-workspace/fips/configs/linux-make-debug.yml
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DFIPS_CONFIG=linux-make-debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DFIPS_USE_CCACHE=OFF -DFIPS_AUTO_IMPORT=ON -B/home/shaurya/fips-workspace/fips-build/liboculus/linux-make-debug -H/home/shaurya/fips-workspace/liboculus
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/lib/ccache/cc
-- Check for working C compiler: /usr/lib/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_BUILD_TYPE: Debug
FIPS_ROOT_DIR: /home/shaurya/fips-workspace/fips
FIPS_PROJECT_DIR: /home/shaurya/fips-workspace/liboculus
FIPS_BUILD_DIR: /home/shaurya/fips-workspace/fips-build
FIPS_DEPLOY_DIR: /home/shaurya/fips-workspace/fips-deploy
FIPS_PROJECT_NAME: liboculus
FIPS_AUTO_IMPORT: ON
FIPS_CONFIG: linux-make-debug
FIPS_PROJECT_BUILD_DIR: /home/shaurya/fips-workspace/fips-build/liboculus/linux-make-debug
FIPS_PROJECT_DEPLOY_DIR: /home/shaurya/fips-workspace/fips-deploy/liboculus/linux-make-debug
Host system: Linux
CMAKE_CXX_COMPILER_ID: GNU
Detected C++ Compiler: GCC (FIPS_GCC)
-- Looking for __atomic_fetch_add_4
-- Looking for __atomic_fetch_add_4 - not found
-- Looking for __atomic_fetch_add_4 in atomic
-- Looking for __atomic_fetch_add_4 in atomic - found
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
FIPS_PLATFORM: Linux
FIPS_PLATFORM_NAME: linux
CMake Warning at /home/shaurya/fips-workspace/fips/cmake/fips.cmake:195 (find_package):
  By not providing "FindPython.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Python", but
  CMake did not find one.

  Could not find a package configuration file provided by "Python" with any
  of the following names:

    PythonConfig.cmake
    python-config.cmake

  Add the installation prefix of "Python" to CMAKE_PREFIX_PATH or set
  "Python_DIR" to a directory containing one of the above files.  If "Python"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:8 (fips_setup)


CMake Error at /home/shaurya/fips-workspace/fips/cmake/fips.cmake:197 (message):
  Python not found, required for code generation!
Call Stack (most recent call first):
  CMakeLists.txt:8 (fips_setup)


-- Configuring incomplete, errors occurred!
See also "/home/shaurya/fips-workspace/fips-build/liboculus/linux-make-debug/CMakeFiles/CMakeOutput.log".
See also "/home/shaurya/fips-workspace/fips-build/liboculus/linux-make-debug/CMakeFiles/CMakeError.log".
[ERROR] Failed to generate 'linux-make-debug' of project 'liboculus'
`
Would appreciate any help! :)
Best Regards

**Comment by Firzen9** [comment]
Hi Aaron,

Sorry for the trouble again. I tried installing with fips but I had an error with 'linux make debug'. I have also tried with different python environments using conda.
I also tried installing with catkin but it says ' Command vcs not found' 
![fips-not-working](https://user-images.githubusercontent.com/64469258/144070555-2bd18712-6b41-4694-b9be-d5e4880b3314.png)
![fips-tools](https://user-images.githubusercontent.com/64469258/144071074-6fc87b2d-2dab-4e8b-b51f-77171f3b7fd2.png)

Best regards,
Shaurya

**Comment by amarburg** [comment]
This sounds like a system package issue.  What version of Linux are you using?  If it's Debian/Ubuntu, can you try `sudo apt install cmake-data`?

**Comment by Firzen9** [comment]
I tried installing cmake-data 3.10.x as well as using cmake version 3.21.x and 3.22 (Also tried installing cmake from scratch). I'm getting a slightly different error with linux-make-debug now. I'm using ubuntu 18.04. 

![fips_notworking](https://user-images.githubusercontent.com/64469258/144238001-e7be8f9b-efb1-4574-aacf-ced9442b8edd.png)
g

**Comment by amarburg** [comment]
Hm, I tried a fips build with a clean checkout of liboculus and it worked.   One thought is that I do use my own fork of fips, so if you happen to be using the upstream version of fips, it may have slightly different behavior.

**Comment by Firzen9** [comment]
Hi Aaron,

So what would you recommend for a fips build? Maybe I could use your fork of fips if possible?

As for building with catkin, (no surprise here), I ran into another error-
![catkin_build](https://user-images.githubusercontent.com/64469258/145128743-92e9eddd-b345-4d3f-8ab5-e8bda88b05fc.png)

Thanks again,
Shaurya

**Comment by amarburg** [comment]
Hi Shaurya,

Hm, I just tried with a clean checkout from Gitlab and didn't have any problems with `vcs` (using vcs version 0.2.6):

```
$ vcs import --input liboculus/liboculus.rosinstall
=== ./g3log_ros (git) ===
Cloning into '.'...
Already on 'main'
Your branch is up to date with 'origin/main'.
```

Your transcript is a little odd .. you installed `python3-vcstool` but the traceback is showing files in the python2.7 directories.   Maybe remove any vcstool packages to see if you have both python2 and python3 versions installed. 



On the fips side, I'd also try a clean checkout .. ideally a separate copy from the Catkin version.   The `fips` script in this repo uses my version of fips, so if you start with a clean checkout that doesn't have a local copy of fips, it will check out my version.

**Comment by lauralindzey** [comment]
Closing -- it's inactive and there's nothing to resolve; so far as we can tell, the fips build works.
